### ISSUE TITLE
AFHTTPRequestOperationManager post 表单数据

### ISSUE THREAD

**Issue by SeanChense** [UESTC-BBS/StudentMe-iOS#2]
AFHTTPRequestOperationManager 中 post 表单数据，尝试了很多方法。
发现只有

            [self.manager POST:[NSURL smLoginString] parameters:data constructingBodyWithBlock:^(id<AFMultipartFormData> formData) {
               
        } success:^(AFHTTPRequestOperation *operation, id responseObject) {
                [subscriber sendNext:responseObject];
                [subscriber sendCompleted];
        } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
                [subscriber sendError:error];
这样才能得到河畔服务器的正确响应。
用 Charles 抓包看到发包不是 form 而是 multipart 跟现有客户端的有区别。
而使用 AFHTTPRequestOperationManager 的另一种 post 方法，直接得到服务器拒绝，返回 html 的文本。

**Comment by SeanChense** [comment]
使用 AFHTTPSessionManager 解决了问题

**Comment by fangjue** [comment]
https://github.com/AFNetworking/AFNetworking#post-url-form-encoded-request

**Comment by fangjue** [comment]
multipart 在上传文件时会用到。

**Comment by SeanChense** [comment]
@fangjue 链接中提到的 post 表单就是我说的
> 而使用 AFHTTPRequestOperationManager 的另一种 post 方法，直接得到服务器拒绝，返回 html 的文本。

AFHTTPSessionManager 也是提供 multipart 的接口可以上传文件的。

**Comment by SeanChense** [comment]
跟 @fangjue 请教了下现在终于明白是怎么回事了。
在 AFNetworking 中 manager 的 request content type 默认情况下是 application/x-www-form-urlencoded

post 一个 dictionary 时就是表单形式的 url 拼接。
然而我错误的添加了 
self.manager.requestSerializer = [AFJSONRequestSerializer serializer]; 处理后就变成了
application/json 形式的了，服务器就拒绝应答。

人丑就该多读书......
